### ISSUE TITLE
[Bug]: Incorrect validation errors of managed webhooks URIs

### ISSUE THREAD

**Issue by patjakubik** [Shopify/cli#4298] opened 2024-08-09 09:17 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Running `shopify app dev` should work fine.

### Actual behavior

Validation fails, unable to run `shopify app dev`. It's weird because it started happening without updating the CLI. I just updated CLI from 3.63.2 to check if the newest version fixes it - but it doesn't. 

### Verbose output

```shell
REDACTED
```

### Reproduction steps

TOML file:

```toml
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "REDACTED"
extension_directories = ["src/extensions/*"]
name = "Example app"
handle = "example"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "example.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://example.com/auth/offline_callback",
  "https://example.com/auth/online_callback",
]

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
uri = "https://example.com/webhooks/customers_data_request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "https://example.com/webhooks/customers_redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "https://example.com/webhooks/shop_redact"
compliance_topics = ["shop/redact"]

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "api/webhooks/app_uninstalled"

[[webhooks.subscriptions]]
topics = ["shop/update"]
uri = "api/webhooks/shop_update"

[pos]
embedded = false
```

### Operating System

macOS 14.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.65.2

**Comment by gonzaloriestra** [comment] 2024-08-09 11:24
Hi!

When it says `webhooks.subscriptions.3.uri`, it actually refers to the 4th element, because the first one would be 0 🤓 . We should probably improve that...

So the problem is with `api/webhooks/app_uninstalled` (and the next one) because it's missing the initial slash. It should be `/api/webhooks/app_uninstalled`.

**Comment by abdulrafaykhatri** [comment] 2024-08-11 11:31
I did faced the same issue with the project initializaed with latest CLI fro different machine

[webhooks.subscriptions.0.uri]: URI format isn't correct. Valid formats include: relative path starting with a slash, HTTPS URL, pubsub://{project-id}:{topic-id} or Eventbridge ARN 

there was app/uninstalled webhook on the 0'th position, however this error reseolved by upgrading to the latest CLI

**Comment by gonzaloriestra** [comment] 2024-08-12 06:11
Yes, that issue was solved in the latest release, so I'm closing here.

Regarding the duplicated slash in Partners, it's not a problem because it should work anyway, like https://www.shopify.com////pricing does. But I'll have a look.

**Closed as completed by gonzaloriestra** 2024-08-12 06:11 UTC
Labels: Type: Bug
