### ISSUE TITLE
[Bug]: `extension_directories` is not working

### ISSUE THREAD

**Issue by aurelienbobenrieth** [Shopify/cli#1324] opened 2023-02-08 14:58 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When specifying a custom path for my extensions in my `shopify.app.toml` as explained [here](https://shopify.dev/apps/tools/cli/structure#root-configuration-file), I should be able to generate extensions in the desired directory.

e.g.
When writing: `extension_directories = ["src/shopify-extensions/*"]` in my `shopify.app.toml` CLI should look for extensions in this directory and not in `extensions/*`.

### Actual behavior

The parameter is totally ignored.

When using `shopify app info` my extensions are not found.

When using `shopify app generate extension` it creates the extension in the default `/extensions` directory.

___

Also, bonus point, why is the `name` property [noted as required](https://shopify.dev/apps/tools/cli/structure#root-configuration-file) if the CLI init an app without it ?

### Reproduction steps

1. `yarn create @shopify/app`
2. Select `node` template
3. Add this line `extension_directories = ["src/shopify-extensions/*"]` to `shopify.app.toml`
4. Run `yarn shopify app generate extension`

5. Enjoy CLI disrespecting your choice and scaffolding the app in `/extensions`

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.41.0

### Node version (run `node -v` if you're not sure)

v19.6

### What language and version are you using in your application?

Node v19.6

**Comment by aurelienbobenrieth** [comment] 2023-02-08 18:45
Thanks for the quick response @Arkham !
Indeed, so there is no way to specify where the CLI is supposed to generate extension ? Not even a flag to add during the command ?
That seems kinda weird to being able to specify where the CLI can find extensions but not where it can be generated 🤔

**Comment by Arkham** [comment] 2023-02-08 18:58
I wasn't here when the decision was made, but I have the feeling the setting was introduced to support legacy projects that had an unconventional directory structure.

Our vision for the future is for all shopify apps to look more or like the same, so if you pick up a new app that you haven't built yourself it would still look familiar to you. But we're definitely open to introducing more options when there is a need :) Would you care to explain a bit more why you want the extensions is a different folder?

**Comment by aurelienbobenrieth** [comment] 2023-02-09 11:31
For the same reasons explained in the [PR that introduced the parameter](https://github.com/Shopify/cli/pull/454).

Basically I am working on a project which is not directly related to a Shopify app. The project is a custom backend written in NestJs that does plenty of things and we want to plug a Shopify App to it.
Our project architecture is already opiniated and we want the extensions to be located where it makes sense for us.

Also, more generally, I can understand your vision of the future. However, I do think developers should be able to get out of the conventional archi that you recommend to fit their needs.
For example, I think that for really complex apps, if you want to implement Clean Archi / DDD / VSA or anything else, the conventional archi is not really a good fit. Yet, developers should still be able (imho) to use the CLI to dev their apps.

**Comment by Arkham** [comment] 2023-02-09 12:24
Thank for your input, I'll relay this to our Product team. I'll close this issue as it's not exactly a bug, but more of an unfortunate case of "working as intended".

**Closed by Arkham** 2023-02-09 12:24 UTC
Labels: Type: Bug, Area: @shopify/app, State: Waiting for feedback

**Comment by aurelienbobenrieth** [comment] 2023-02-09 13:28
Okay !

I'd be glad if you could keep me up to date about this in the upcoming package updates.
