### ISSUE TITLE
CLI should not clobber `.env` files

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/cli#4704] opened 2024-10-21 18:24 UTC
I have a `.env` file in my project for configuring a number of development/local ENV vars. After running `shopify app deploy` this file was clobbered and all of the organization within the file is gone and all of the comments documenting exactly what each value represents were removed. The file is not under source control since it contains secrets, so now all of that is just gone. This feels extremely hostile.

**Comment by isaacroldan** [comment] 2024-10-25 14:22
Hi @jagthedrummer, this is definitely a bug. The intention is to just append or update specific keys in the .env, without affect the existing content. Apologies for the inconvenience caused by this bug.

A fix for this issue will be released in the next CLI version (3.70), it should be out in a couple weeks.

**Closed** 2024-10-31 17:34 UTC
Labels: Area: @shopify/app
