### ISSUE TITLE
Running shopify app config link fails with "Fix a schema error in shopify.app.toml"

### ISSUE THREAD

**Issue by erandagan** [Shopify/cli#3643] opened 2024-04-02 10:58 UTC
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system: MacOS Sonoma
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

Running `yarn shopify app config link` should generate a `shopify.app.toml` configuration file for an existing app.

## Actual behavior

The command fails with "Fix a schema error in shopify.app.toml", **even if there was no `shopify.app.toml` to begin with.** It seems like it generates a half-baked configuration file before it fails:

```
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "XXX"
```

## Steps to reproduce the problem

1. Remove your existing shopify.app.toml
2. Try to link an existing app.

## Debug logs

```
// Paste any relevant logs here
```

**Comment by amcaplan** [comment] 2024-04-03 10:25
Hi @erandagan, thanks for getting in touch! We have a few other issues opened about the same thing, and plan to release a patch shortly for this.

@lizkenyon FYI you couldn't reproduce because this only affects apps created before app configuration was managed in the TOML. So a new app wouldn't experience this problem.

**Comment by amcaplan** [comment] 2024-04-03 10:52
3.58.1 is out, and should solve this problem! I'm closing this issue, as I believe it's solved, but please do let us know if you continue to experience any trouble.

**Closed by amcaplan** 2024-04-03 10:52 UTC
