### ISSUE TITLE
[Bug]: ExtensionTimeoutError: Extension timed out while mounting

### ISSUE THREAD

**Issue by saadsaif97** [Shopify/cli#2423] opened 2023-07-12 18:25 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

(_JavaScript React_) **checkout ui extension** should be displayed in the checkout for the development preview and hot reloading should be available.

I scaffold a checkout ui extension (_JavaScript React_) using the command: `yarn generate extension`

I cannot preview the extension in the preview mode from the developer console.
I saw the browser console and found that there was the following error: 
`Extension gid://shopify/LocalActivatedExtension/10 timed out while mounting at app.latest.en.97a3a614ace092cfb047.js:1:198739`

But when I create the extension using _Javascript_ only without react, it mounts well and I can see the hot reloading.

when we deploy the app, we can use (_JavaScript React_) **checkout ui extension** as well in the checkout.

### Actual behavior

(_JavaScript React_) **checkout ui extension** was not being displayed in the checkout and I saw the following error in the browser console:
```ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/10 timed out while mounting at app.latest.en.97a3a614ace092cfb047.js:1:198739```

### Verbose output

```shell
Extension gid://shopify/LocalActivatedExtension/10 timed out while mounting at app.latest.en.97a3a614ace092cfb047.js:1:198739
```

### Reproduction steps

1. create a checkout ui extension using the command: `yarn generate extension`
2. selection extension type `Checkout UI` and give any name
3. then select `JavaScript React`

then preview the extension on the store where [Checkout Extensibility](https://shopify.dev/api/release-notes/developer-previews?locale=en#checkout-extensibility-developer-preview) preview is enabled.

the checkout UI extension will not render on the checkout page for the development preview.

You can see the following error in the console:
```ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/10 timed out while mounting at app.latest.en.97a3a614ace092cfb047.js:1:198739```

### Operating System

Ubuntu 22.04.2 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47.5

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Node 18.12.1

**Comment by saadsaif97** [comment] 2023-07-14 11:11
Hi @alvaro-shopify  I created a new app and generated a new extension using javascript react.

I also see this error on top: 
`Failed to load resource: the server responded with a status of 401 ()` `/private_access_tokens?id=81fa53494bc9202aa657f6d0342df6b0&checkout_type=c1` 

maybe I am missing something.

![image](https://github.com/Shopify/cli/assets/58517683/8ae8f734-da87-44af-868b-661a02fe1bef)

**Comment by lushuiyu** [comment] 2023-08-09 03:09
I had the same problem.
I create extensions according to the official documentation.
when i input `yarn dev`, i got this error

1. ExtensionTimeoutError: Extension 89818956064 timed out while mounting

    at app.esm.en.e9488b4febfcf0fcf7b3.js:1:399459
542.esm.en.8a89bc5419905a2a5285.js:2 

2. ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/00 timed out while mounting

    at app.esm.en.e9488b4febfcf0fcf7b3.js:1:399459

**Comment by hashemHP** [comment] 2023-09-08 10:49
Hi, extensions were working fine on Dev and published stores, now suddenly it's not working on dev store, and though 
`ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/10 timed out while mounting`

**Comment by ploiid10** [comment] 2023-09-08 11:41
Yep, happening on my side as well.
ExtensionTimeoutError: Extension 65072759082 timed out while mounting

**Comment by michaelr231** [comment] 2023-09-26 10:17
some one figure it out?

**Comment by hashemHP** [comment] 2023-09-27 17:43
as [alvaro-shopify](https://github.com/alvaro-shopify)  mentioned, "It's related to some kind of temporary service unavailability, "
save your time and try again later and it will be fine

**Comment by kumar303** [comment] 2023-10-04 14:35
> I can see the network request to /extensions endpoint.

Since you can see that the network request is successful (200), one possible explanation is that your [rendered extension target](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview) does not match your [configured extension target](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration).

For example, if you have this in your config:

```toml
[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./Checkout.jsx"
```

and you have this in `Checkout.jsx`:

```jsx
export default reactExtension(
  'purchase.cart-line-item.line-components.render',
  () => <Extension />,
);
```

then you will get a timeout error.

**Comment by huzaifaarain** [comment] 2023-10-20 16:53
> > I can see the network request to /extensions endpoint.
> 
> If you can see the network request is successful (200) for both that and the JS bundle itself, one possible explanation is that your [rendered extension target](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview) does not match your [configured extension target](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration).
> 
> For example, if you have this in your config:
> 
> ```toml
> [[extensions.targeting]]
> target = "purchase.checkout.block.render"
> module = "./Checkout.jsx"
> ```
> 
> and you have this in `Checkout.jsx`:
> 
> ```js
> export default reactExtension(
>   'purchase.cart-line-item.line-components.render',
>   () => <Extension />,
> );
> ```
> 
> then you will get a timeout error.

I believe this is not the case, it does work sometimes and sometimes it doesn't. There has to be some other issue.

**shopify.extension.toml**

```toml
[[extensions.targeting]]
module = "./src/Targets/Block/PurchaseCheckoutBlockRender.jsx"
target = "purchase.checkout.block.render"
```

```js
import { reactExtension } from "@shopify/ui-extensions-react/checkout";
import React from "react";
export default reactExtension("purchase.checkout.block.render", () => <HealthCheck />);

function HealthCheck() {
  console.log("purchase.checkout.block.render loaded");
  return null;
}
```

I am still facing the error 

`ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/00 timed out while mounting
    at app.latest.en.e593c84487d3679854fa.js:1:454394`

**Comment by saadsaif97** [comment] 2023-10-24 18:26
JUST restart the dev server and make sure you imports are correct and extension targets are matching in the `Checkout.jsx` and `shopify.extension.toml`
sometimes it works after 2-3 restarts...

**Comment by pramod-praella** [comment] 2023-11-14 01:43
facing the same issue.

> JUST restart the dev server and make sure you imports are correct and extension targets are matching in the `Checkout.jsx` and `shopify.extension.toml` sometimes it works after 2-3 restarts...

check all the things but not work at all. anyone figure it out

**Comment by yadsgroup** [comment] 2024-01-17 14:30
Any news about that issue? I can see my extension 1 out of 100 times, other times it timeout...

**Comment by willfranklyn** [comment] 2024-02-21 21:24
I am currently facing this issue. Changing my shopify.extension.toml target variable solves the extension timeout issue but I am still getting the 401 (Unauthorized) on the private_access_token request and my extension is not appearing in my checkout preview. I'll try messing around with a few things to see if I can fix it.

**Comment by FilipposDe** [comment] 2024-03-16 16:46
In my case this happened due to a typo in the first arg of the `reactExtension` function.

**Comment by kumar303** [comment] 2024-05-10 21:39
Since this is not a CLI bug, I will close it in favor of https://github.com/Shopify/ui-extensions/issues/1957

@wissem the new bug (above) enumerates all the way to reproduce a timeout. Maybe that will help you track down the issue.

**Closed by kumar303** 2024-05-10 21:39 UTC
Labels: Type: Bug, Area: @shopify/app

**Comment by hashemHP** [comment] 2024-05-19 15:22
Today. I experienced the same issue, did use [ngrok tunnel ](https://shopify.dev/docs/api/shopify-cli/app/app-dev#flags-propertydetail-tunnelurlvalue)and it worked fine

**Comment by Skriptach** [comment] 2024-08-22 10:04
> > [saadsaif97](/saadsaif97)
> 
> I had the same problem, but I think it worked out.
> 
> 1. open your file "shopify.extension.toml"
> 2. open this config => network_access = true
> 3. reset your app

Thank you. This is worked for me
