### ISSUE TITLE
[Bug]: Checking out app extension on new machine, no app commands

### ISSUE THREAD

**Issue by martijnarts** [Shopify/cli#128] opened 2022-07-07 13:08 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

After checking out a repository with a Shopify App Extension set up on a new machine, I should be able to run `$ npm run shopify -- app dev` and get prompted for authentication info and other env setup.

### Actual behavior

No app commands are found, for example:

```
$ npm run shopify -- app dev                                                                                                                                                 1 ↵  ✹switch-to-typescript

> rckive-shopify-integration@1.0.0 shopify
> shopify "app" "dev"


━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    command app:dev not found

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

1. Create a new app extension
2. Delete `web/` folder
3. Check out repo on machine without Shopify CLI setup (or maybe with?)

Not super sure if this is an accurate reproduction, we may have gotten ourselves into a weird state here by deleting the `web/` folder (which we don't need).

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.27

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.13.0

**Comment by gonzaloriestra** [comment] 2022-07-08 10:45
Hi! The command should be `npm run shopify app dev` or just `npm run dev`.

The `--` is only required when you want to pass any flag, as explained here: https://shopify.dev/apps/tools/cli/commands#command-syntax

Let me know if you find any other problem.

**Comment by martijnarts** [comment] 2022-07-08 10:49
Hi @gonzaloriestra, running `npm run shopify -- app dev` was just me trying out different ways of accessing the command, I also tried this with `npm run dev`, `npm run shopify app dev`, `npm run shopify app:dev` and I think some others. So that's not the cause here.

**Comment by martijnarts** [comment] 2022-07-11 10:18
I did run `npm install`, and my dependencies look like this:

```
  "dependencies": {
    "@shopify/admin-ui-extensions-react": "^1.0.1",
    "@shopify/app": "3.0.24",
    "@shopify/cli": "3.0.24",
    "react": "^17.0.2"
  },
```

**Comment by gonzaloriestra** [comment] 2022-07-11 12:02
Have you tried removing `node_modules` and then calling `npm install` again?

Anyway, it looks like it's not a problem with the CLI, but with your local environment or that repository, so I'm closing here.

I've tried to replicate it by following these steps, but it worked as expected:
- Create a new app and an extension
- Remove the `web` folder
- Copy the app folder to another place
- Remove the `node_modules` and run `npm install`
- `npm run dev`

**Closed by gonzaloriestra** 2022-07-11 12:02 UTC
Labels: Type: Bug, State: Waiting for feedback

**Comment by martijnarts** [comment] 2022-07-11 19:46
For future reference: the Shopify CLI is not compatible with Node v16. Updating to v18 fixed the problem.

**Comment by gonzaloriestra** [comment] 2022-07-12 07:04
@martijnarts There are many people using Node v16 (and it's the version I used above)... If you share detailed reproduction steps, I'm happy to investigate.

**Comment by monting** [comment] 2022-07-18 16:20
I think I'm seeing related behavior when I try to deploy a vanilla Shopify node app to Vercel/Heroku.

In the build during deploys, I get:
```
remote:        > shopify app build
remote:
remote:
remote: ━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
remote:     command app:build not found
remote:
remote: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

When I change the build script to `"build": "shopify help",`, I get:

```
remote:        > shopify help
remote:
remote:        A CLI tool to build for the Shopify platform
remote:
remote:        VERSION
remote:          @shopify/cli/3.0.27 linux-x64 node-v16.15.1
remote:
remote:        USAGE
remote:          $ shopify [COMMAND]
remote:
remote:        TOPICS
remote:          auth   Auth operations
remote:          ngrok  Manage ngrok tunnels
remote:
remote:        COMMANDS
remote:          help  Display help for shopify.
remote:          logs  View full debug logs from the Shopify CLI
```

So it looks like the `app` command isn't available in the deploy build environment for some reason?

Versions:
```
remote:        engines.node (package.json):  16.15.1
remote:        engines.npm (package.json):   8.13.1
```
