### ISSUE TITLE
[Bug]: Section Scheme "class is invalid" for valid classes

### ISSUE THREAD

**Issue by JasonHassold** [Shopify/cli#4871] opened 2024-11-17 23:49 UTC
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Should accept any valid class

### Actual behavior

The Shopify CLI rejects the section file when I include a class with certain special characters like `[` or `]` and likely others with the error message "Invalid schema: class is invalid". In this case I'm using the class `tw-z-[110]` because I'm using Tailwind CSS which uses these and other special characters for classes. Although this isn't super common outside of Tailwind, classes containing these special characters are valid and shouldn't be rejected.

### Verbose output

```shell
╭─ error ─────────────────────────────────────────────────────────────────────╮
│                                                                             │
│  Failed to upload file "sections/nav.liquid" to remote theme.               │
│                                                                             │
│                                                                             │
│                                                                             │
│  - Invalid schema: class is invalid                                         │
│                                                                             │
╰─────────────────────────────────────────────────────────────────────────────╯
```

### Reproduction steps

1. Have the Shopify CLI running in dev mode
2. Create a section schema that has the "class" field and enter a class containing `[` or `]` and save

### Operating System

Ubuntu 20.04.6 LTS on WLS 2 on Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.69.4

**Comment by JasonHassold** [comment] 2024-11-18 23:01
@lucyxiang that makes sense but then where should this be reported to? I don't know where else would be appropriate to report it

**Comment by lukeh-shopify** [comment] 2024-11-21 00:39
Hi @JasonHassold, this is a duplicate of https://github.com/Shopify/cli/issues/2003 and https://github.com/Shopify/cli/issues/3184.

We know about this internally but do not have a solution at the moment. Please see [this comment](https://github.com/Shopify/cli/issues/3184#issuecomment-2161761568). I will be closing the issue as it is not relevant to the Shopify CLI

**Closed by lukeh-shopify** 2024-11-21 00:39 UTC
Labels: Type: Bug, Area: @shopify/theme
