### ISSUE TITLE
Rationalize spacing between UI elements

### ISSUE THREAD

**Issue by MeredithCastile** [Shopify/cli#1144] opened 2023-01-18 20:21 UTC
@matteodepalo, @Arkham, and I discussed how to ensure predictable spacing between elements. Here are examples where this comes up:

- [ ] Currently, there's excessive spacing between prompt and success banner after the task runner bar disappears. How might we address that?

- [x] If we have an info box next to a success box (ex: info box with your URLs changed; success banner after dev succeeds), let's not have double spacing between them.

- [x] If we have a non-componentized line of copy above or below a component, can we ensure standard spacing between those elements?

### Meta-questions
- What should we enforce programmatically?
- What's just better left to the devs building into the CLI?

### Why this matters

Spacing is key to our design value around visually scannable semantic groupings. 

![Image](https://user-images.githubusercontent.com/51347120/213288286-467c5e0a-f047-4f81-88be-cded79098fd7.png)

**Comment by matteodepalo** [comment] 2023-01-19 13:09
> Currently, there's excessive spacing between prompt and success banner after the task runner bar disappears. How might we address that?

This is a problem I've tried to address, but I didn't find an easy solution. The root of the issue is that when we make the progress component disappear we cannot avoid leaving a blank line. There is no way to remove a single line from the terminal.

For cases when there is a success banner after tasks complete, we could have the banner be the final state of the progress component. This would solve the issue. But if we just have tasks that complete and we want to forget about them I'm not sure there is a solution.

> If we have an info box next to a success box (ex: info box with your URLs changed; success banner after dev succeeds), let's not have double spacing between them.

This should already be taken care of by UI kit.

>  If we have a non-componentized line of copy above or below a component, can we ensure standard spacing between those elements?

We could in theory introduce `renderText` which would just print some text and ensure correct spacing is applied.

**Comment by matteodepalo** [comment] 2023-02-27 02:04
I'll close this as I've introduced `renderText`. We'll have to live with the extra space after tasks are being rendered for now, I didn't find any way to remove the final blank line.

**Closed by matteodepalo** 2023-02-27 02:04 UTC
Labels: Area: UI & content, no-issue-activity
