### ISSUE TITLE
[Bug]: Issue with the reverse proxy for backend served architecture

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#1118] opened 2023-01-17 03:16 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Hi,

I am trying to get a grasp of the new architecture for apps, but after many attempts with the PHP boilerplate project, I could not find the logic behind some of the choices. I have therefore tried to simplify the whole structure which makes more sense to me, managed to somewhat make it works, but now hit a blocking road.

My structure is the following:

```
- backend
  -- shopify.web.toml (with a backend type)
- frontend
  -- shopify.web.toml (with a frontend type)
```

The frontend uses ESbuild to compile, and save the result into the /backend/assets folder. The Polaris app is therefore being served by the _backend_ app.

However, I still want to have the shopify.web.toml so that when I use "shopify app dev", it runs both the backend and the frontend code that is in charge of building the code with ESBuild.

Everything starts correctly: Shopify CLI properly launch the backend and frontend commands. No error appears at this stage.

<img width="810" alt="Capture d’écran 2023-01-17 à 12 11 36" src="https://user-images.githubusercontent.com/1198915/212801694-eb453643-e2a6-469d-b7f2-ee7c8c64a3a2.png">

But as soon as I start the app, this error appears:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/1198915/212801753-ee9e120c-c51f-42e1-8123-fd8ff1e6b32d.png">

I tried to read the source of the dev command, and the issue seems to be coming from the fact that the frontend apparently setup a reverse proxy, and hitting the ngrok URL hit this instead of going to the backend serving the frontend.

Said otherwise, I would like to have a "frontend" environment whose _only_ purpose is to launch the commands to build and watch the frontend environment, without setting the whole Vite and proxy server complexity. Maybe through a proxy option:

```
type="frontend"
proxy=false

[commands]
dev = "npm run dev"
build = "npm run build"
```

How would that be possible under the current architecture?

Let me know if anything is unclear.

### Actual behavior

An error is shown

### Reproduction steps

1.
2.
3.

### Operating System

OSX

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.33

**Comment by ozzyonfire** [comment] 2023-01-20 15:50
Same problem. It was reported a while ago in issue #750 and #703. Those got automatically closed because they were hanging out for too long. So we should try to make sure this issue doesn't do the same thing. 

What kind of app are you building/running, node, express? Is it a typescript app? Are you using nodemon to watch for changes?

**Comment by bakura10** [comment] 2023-01-21 06:39
Hi @ozzyonfire .

I will try to add a message here every 10 days to ensure this issue is not closed automatically :/.

I am trying to do an app in PHP (to help a co-worker who actually build something in Rails). The main difference is that we want our entry point to be the backend (that serves the Polaris app) and not the frontend (as all the starter of Shopify are doing) but still be able to take advantage of the frontend/backend stuff to be able to build automatically our environments.

**Comment by bakura10** [comment] 2023-02-15 04:27
Still relevant, do not close it.

**Comment by amcaplan** [comment] 2023-06-04 20:57
Going to reopen as I'm actually working on this...

Did some digging and here's the current state of my understanding:

1. We do need to proxy the frontend always, because [the proxy is also responsible for forwarding `/extensions` paths to the dev console](https://github.com/Shopify/cli/blob/565dee129e580191997c99662dd67ee4bb0e167c/packages/app/src/cli/services/dev.ts#L186).
2. The primary role of `frontend` is that it's the URL for the embedded app. The primary role of `backend` is that its port will be passed as `BACKEND_PORT` in the web ENV, so the frontend knows how to access it. Nothing about these is mutually exclusive. So we should be able to specify a web as both `frontend` and `backend`, and the only reason we can't is that `type` only accepts a single string.
    @bakura10 I believe that in your case, first you tried setting `frontend` to a process without a web server, which didn't work, and then (based on my advice) you correctly set the server as `frontend` but then the background process was set as `backend` and the embedded app tried to call to it which obviously it couldn't. What you actually would want to do is set your process with a server as both `backend` and `frontend`.
3. We don't currently have a role for processes which simply run and aren't actually used for anything beyond that. This seems to be hampering your efforts, and I agree it doesn't make much sense.

I opened a [PR](https://github.com/Shopify/cli/pull/2083) to allow a string array of `roles` instead of just 1 `type`, so in the monolith case you can just set `roles = ["frontend", "backend"]` and all relevant behaviors will be applied. A third role is introduced, `"background"`, which is for any web process that needs to run along with the other webs but isn't the embedded app or its direct backend.

I'd like to check that this would help in your scenario. @bakura10 would it perhaps be possible to provide a minimal reproduction, so I can check that this solution solves the problem you're facing?

**Comment by bakura10** [comment] 2023-06-05 03:46
Hi @amcaplan ,

I don’t actively do app dev, actually I was trying to help the app team at Maestrooo so did some experiments. But yes, the issue was that my backend was also serving the front end so it was both a front and backend.

What confused me the most actually I think was the architecture of the node template: https://github.com/Shopify/shopify-app-template-node/tree/main/web

the fact that the front end was actually contained inside the backend while the two apps are completely dissociated increased my initial confusion.

**Comment by mondragon-ai** [comment] 2023-06-07 15:26
Currently with similar issues. This happened after publishing the app for review. 

Every time I run `npm run dev` I get the following errors:
![Screenshot 2023-06-07 at 10 06 10 AM](https://github.com/Shopify/cli/assets/73964490/602b96a6-0508-44e9-9568-ebfa5f57a1a5)

The shopify.web.toml file in my /web/frontend folder is as follows:
`type="frontend"`

`[commands]`
`dev = "npm run dev"`
`build = "npm run build"`

Here is the root shopify.app.toml file:
`name = "Sherpa"`
`scopes = "read_all_orders,read_products,read_orders,write_orders,read_customers,write_customers,write_discounts"`
`extension_directories = ["extensions/*"]`
`web_directories = ["web/*"]`

Here is my vite.config.js file (not changed since creating the project):
![Screenshot 2023-06-07 at 10 10 30 AM](https://github.com/Shopify/cli/assets/73964490/dffe68ca-1e5d-49cf-896d-8e9c362359e1)

When pressing "p" in the terminal to open the oAuth installation process I get these errors as well. 
![Screenshot 2023-06-07 at 10 12 41 AM](https://github.com/Shopify/cli/assets/73964490/f22429b2-e3fe-4e58-b379-badbea3a1b09)

Shopify gave me comments and I need to edit the app to make the adjustments, but I am not able to view my embedded app as a result. 

I have uninstalled and reinstalled it as suggested here: https://community.shopify.com/c/shopify-apis-and-sdks/app-refused-to-connect-nodejs-amp-express/td-p/515260

I also read somewhere on Shopify forum to run `shopify auth logout`, clear my cache, close all windows, and run `npm run dev -- --reset` with no luck.

Here is my environment: `VERSION @shopify/cli/3.46.2 darwin-x64 node-v20.2.0`

Root package.json:
![Screenshot 2023-06-07 at 10 25 32 AM](https://github.com/Shopify/cli/assets/73964490/4fedd71b-85c7-4435-89c9-85a1fb2ab8f9)

Web package.json:
![Screenshot 2023-06-07 at 10 26 04 AM](https://github.com/Shopify/cli/assets/73964490/bd278b28-967e-4040-a651-931116f4509d)

**Comment by amcaplan** [comment] 2023-06-29 09:32
There are some backwards-compatible changes in the latest release (`3.47`) that should solve this issue.

You can now have the monolith use `roles = ["frontend", "backend"]` instead of `type`, and you can have the non-serving process use `roles = ["background"]`.

Still working on documentation updates, but this solution should work for the originally mentioned case.

**Comment by amcaplan** [comment] 2023-07-22 19:09
Documentation has been updated, so going to close this.

**Closed by amcaplan** 2023-07-22 19:09 UTC
Labels: Type: Bug, Area: @shopify/app, no-issue-activity
