### ISSUE TITLE
[Bug]: .jsx files are not resolved when building the app

### ISSUE THREAD

**Issue by alanhill** [Shopify/cli#805] opened 2022-11-23 13:51 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

.jsx files are able to be resolved when imported

### Actual behavior

.jsx files cannot be resolved, you can have an index.jsx, however any files imported need to e .js

### Reproduction steps

1. Generate an extension with .jsx
2. Import a file into index.jsx with a .jsx file extension
3. Try to build the app

### Operating System

Mac Ventura 13.0.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

**Comment by alvaro-shopify** [comment] 2022-11-24 12:14
Hi @alanhill !. Thanks for reporting this issue.

I'm not able to reproduce the issue:
- I have generated a new `checkout UI extension` selecting `Javascript Reat`
- I have created a new `other.jsx` file at the same level than `index.jsx`
- I have added a simple method that returns an string in `other.jsx`
- I have imported in `index.jsx` the method like this `import { test } from './other.jsx';`
- I have run the CLI command `yarn shopify app build` and it finishes well
- I have also run the CLI command `yarn shopify app dev` and I can preview the extension

Do I miss something with these steps?.

Best regards

**Comment by alanhill** [comment] 2022-12-16 14:42
Sorry missed your comment - I was using an admin extension, not sure if that would make a difference. But yes, those were the steps (other then we were running the cli command from within the cli repo).

**Comment by isaacroldan** [comment] 2023-01-04 15:25
Hi @alanhill !

Take into account that you need to include the `.jsx` extension in the import like `import { foo } from './foo.jsx'
Just tested with an admin extension and it works this way :)

Closing the issue, feel free to reopen if you find any other problem!

**Closed by isaacroldan** 2023-01-04 15:25 UTC
Labels: Type: Bug
