### ISSUE TITLE
[Bug]: "Unexpected" error when adding multi page extension

### ISSUE THREAD

**Issue by edhgoose** [Shopify/cli#3984] opened 2024-06-05 18:03 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I expected that when following https://shopify.dev/docs/apps/build/checkout/best-practices/create-multi-page-extensions#post-purchase that I'd be able to create an extension which is present in two injection points.

### Actual behavior

I received an error saying:

```
✘ [ERROR] Unexpected "thankYouRender"

extensions/post-purchase-ui/src/PostPurchase.tsx:20:7:
20 export thankYouRender;
╵ ~~~~~~~~~~~~~~
```

### Verbose output

```shell
$ yarn --verbose run deploy
yarn run v1.22.22
verbose 0.151983541 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.npmrc".
verbose 0.152149 Found configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.npmrc".
verbose 0.15228175 Checking for configuration file "/Users/ed.hartwellgoose/.npmrc".
verbose 0.152344375 Checking for configuration file "/opt/homebrew/Cellar/node@18/18.19.0/etc/npmrc".
verbose 0.152497041 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.npmrc".
verbose 0.152615791 Found configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.npmrc".
verbose 0.152726833 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/.npmrc".
verbose 0.152862208 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/.npmrc".
verbose 0.152913041 Checking for configuration file "/Users/ed.hartwellgoose/.npmrc".
verbose 0.153033791 Checking for configuration file "/Users/.npmrc".
verbose 0.153803583 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.yarnrc".
verbose 0.153863625 Checking for configuration file "/Users/ed.hartwellgoose/.yarnrc".
verbose 0.154018958 Found configuration file "/Users/ed.hartwellgoose/.yarnrc".
verbose 0.154127958 Checking for configuration file "/opt/homebrew/Cellar/node@18/18.19.0/etc/yarnrc".
verbose 0.154201333 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/mention-me/.yarnrc".
verbose 0.1542435 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/shopify/.yarnrc".
verbose 0.154278083 Checking for configuration file "/Users/ed.hartwellgoose/OtherProjects/.yarnrc".
verbose 0.154325916 Checking for configuration file "/Users/ed.hartwellgoose/.yarnrc".
verbose 0.154381041 Found configuration file "/Users/ed.hartwellgoose/.yarnrc".
verbose 0.1544815 Checking for configuration file "/Users/.yarnrc".
verbose 0.155814083 current time: 2024-06-05T17:57:32.112Z
$ shopify app deploy
╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                           │
│  Using .env:                                                                                                                              │
│                                                                                                                                           │
│    • Org:             Mention Me Ltd                                                                                                      │
│    • App:             mention-me                                                                                                          │
│    • Include config:  Yes                                                                                                                 │
│                                                                                                                                           │
│   You can pass `--reset` to your command to reset your app configuration.                                                                 │
│                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

?  Release a new version of mention-me?
✔  Yes, release this new version


Releasing a new app version as part of mention-me

checkout-journey │ Bundling UI extension checkout-journey...
post-purchase-ui │ Bundling UI extension post-purchase-ui...

✘ [ERROR] Unexpected "thankYouRender"

    extensions/post-purchase-ui/src/PostPurchase.tsx:20:7:
      20 │ export thankYouRender;
         ╵        ~~~~~~~~~~~~~~

╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                           │
│  Build failed with 1 error:                                                                                                               │
│  extensions/post-purchase-ui/src/PostPurchase.tsx:20:7: ERROR: Unexpected "thankYouRender"                                                │
│                                                                                                                                           │
│  To investigate the issue, examine this stack trace:                                                                                      │
│    at (extensions/post-purchase-ui/src/PostPurchase.tsx:20)                                                                               │
│    at failureErrorWithLog (esbuild/lib/main.js:1650)                                                                                      │
│    at (esbuild/lib/main.js:1058)                                                                                                          │
│    at runOnEndCallbacks (esbuild/lib/main.js:1485)                                                                                        │
│    at buildResponseToResult (esbuild/lib/main.js:1056)                                                                                    │
│    at (esbuild/lib/main.js:1068)                                                                                                          │
│    at new Promise                                                                                                                         │
│    at on-end (esbuild/lib/main.js:1067)                                                                                                   │
│    at handleRequest (esbuild/lib/main.js:731)                                                                                             │
│    at handleIncomingPacket (esbuild/lib/main.js:756)                                                                                      │
│    at readFromStdout (esbuild/lib/main.js:679)                                                                                            │
│                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

    Error: Build failed with 1 error:
    extensions/post-purchase-ui/src/PostPurchase.tsx:20:7: ERROR: Unexpected "thankYouRender"
verbose 8.461980041 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:750:123)
    at new ProcessTermError (/Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:790:113)
    at /Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:34408:30
    at Generator.throw (<anonymous>)
    at step (/Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:310:30)
    at /Users/ed.hartwellgoose/.cache/node/corepack/yarn/1.22.22/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1. Create an extension. 
2. Make two injection points as per the article above. 
3. Try and run `yarn run deploy`

Example code:

From PostPurchase.tsx:
```
const thankYouRender = reactExtension(
	"purchase.thank-you.block.render",
	() => <Extension />
);
export thankYouRender;

const orderStatusRender = reactExtension(
	"customer-account.order-status.block.render",
	() => <Extension />
);
export orderStatusRender;
```

And from shopify.extension.toml:

```
[[extensions.targeting]]
module = "./src/PostPurchase.tsx"
target = "purchase.thank-you.block.render"
export = "thankYouRender"

[[extensions.targeting]]
module = "./src/PostPurchase.tsx"
target = "customer-account.order-status.block.render"
export = "orderStatusRender"
```

These are the only things I've changed from the working app.

The working app has this instead:

PostPurchase.tsx - note the `default` and the removal of `orderStatusRender`:
```
const thankYouRender = reactExtension(
	"purchase.thank-you.block.render",
	() => <Extension />
);
export default thankYouRender;
```

And in shopify.extension.toml - note the absence of the order status block

```
[[extensions.targeting]]
module = "./src/PostPurchase.tsx"
target = "purchase.thank-you.block.render"
export = "thankYouRender"
```

### Operating System

Mac OS Sonoma 14.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.61.0 darwin-arm64 node-v18.19.0

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v18.19.0

### What language and version are you using in your application?

Typescript

**Comment by gcraftyg** [comment] 2024-06-20 23:58
This looks like an issue with the export statements in the sample code in our docs. The export should be alongside the variable definition or as a separate export. I confirmed that changing to one of these two resolves the issue.

```
// export at the definition
export const thankYouRender = reactExtensions("...
export const orderDetailsRender = reactExtensions("...

// or export as a separate object
const thankYouRender = reactExtensions("...
const orderDetailsRender = reactExtensions("...

export {thankYouRender, orderDetailsRender}
```

I think we should update these docs with the correct syntax so that it is correct, but we planned to move away from this way of exporting multiple targets in favor of a [single target per extension file](https://github.com/Shopify/checkout-web/issues/30106)

**Comment by isaacroldan** [comment] 2024-07-02 09:11
Since this is not a CLI issue and is already being tracked in https://github.com/Shopify/ui-extensions/issues/2004 i'll be closing this issue. 

Feel free to open a new one if you find any issue with the CLI!

**Comment by edhgoose** [comment] 2024-07-02 18:58
Hi @isaacroldan - I was being a bit cheeky in asking the question about https://github.com/Shopify/ui-extensions/issues/2004 here. I had a response here, and saw there was no response over there so hoped to attract the attention of someone.

I'd argue this issue (the original one, about the `unexpected error`) is still an issue, and the documentation in the [link above](https://shopify.dev/docs/apps/build/checkout/create-multi-page-extensions#post-purchase) is incorrect.

Could we keep it open until the issue is resolved?

**Comment by isaacroldan** [comment] 2024-07-04 09:47
Hi @edhgoose! You are right, sorry about that, i was able to reproduce the original issue.
I'll pass this to the appropriate team so that they can update the docs.

The correct way to make the export is:
```
export {thankYouRender};
```

**Comment by isaacroldan** [comment] 2024-07-04 13:56
Docs have been updated @edhgoose 
https://shopify.dev/docs/apps/build/checkout/create-multi-page-extensions

**Closed by isaacroldan** 2024-07-04 13:56 UTC
Labels: Type: Bug

**Comment by edhgoose** [comment] 2024-07-04 14:57
Thanks @isaacroldan !
