### ISSUE TITLE
[Bug]: CLI command "shopify theme list" returns error

### ISSUE THREAD

**Issue by JimStrive** [Shopify/cli#1111] opened 2023-01-16 14:42 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should have returned a list of the available themes

### Actual behavior

Returned an error, also gave me a login page key return prompt which didn;t complete or allow me to use as the error terminated the command.

### Stack trace

```shell
$ shopify theme list


To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  process.stdin.setRawMode is not a function                                  │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at (../AppData/Roaming/nvm/v14.19.3/node_modules/@shopify/theme/node_mod  │
│    ules/@shopify/cli-kit/src/ui.ts:203)                                      │
│      process.stdin.setRawMode(true)                                          │
│    at new Promise                                                            │
│    at keypress (../AppData/Roaming/nvm/v14.19.3/node_modules/@shopify/theme  │
│    /node_modules/@shopify/cli-kit/src/ui.ts:188)                             │
│      return new Promise((resolve, reject) => {                               │
│    at authorize (../AppData/Roaming/nvm/v14.19.3/node_modules/@shopify/them  │
│    e/node_modules/@shopify/cli-kit/src/session/authorize.ts:45)              │
│      await keypress()                                                        │
│    at processTicksAndRejections (internal/process/task_queues.js:95)         │
│    at async executeCompleteFlow (../AppData/Roaming/nvm/v14.19.3/node_modul  │
│    es/@shopify/theme/node_modules/@shopify/cli-kit/src/session.ts:319)       │
│      const code = await authorize(scopes)                                    │
│    at async ensureAuthenticated (../AppData/Roaming/nvm/v14.19.3/node_modul  │
│    es/@shopify/theme/node_modules/@shopify/cli-kit/src/session.ts:215)       │
│      newSession = await executeCompleteFlow(applications, fqdn)              │
│    at async ensureAuthenticatedAdmin (../AppData/Roaming/nvm/v14.19.3/node_  │
│    modules/@shopify/theme/node_modules/@shopify/cli-kit/src/session.ts:151)  │
│      const tokens = await ensureAuthenticated({adminApi: {scopes,            │
│      storeFqdn: store}}, process.env, forceRefresh)                          │
│    at run (../AppData/Roaming/nvm/v14.19.3/node_modules/@shopify/theme/src/  │
│    cli/commands/theme/list.ts:19)                                            │
│      const adminSession = await session.ensureAuthenticatedThemes(store,     │
│      flags.password)                                                         │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

### Reproduction steps

1. Installed CLI
2. Ran command
3. Error

### Operating System

windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.33.0

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

v14.19.3

**Comment by amcaplan** [comment] 2023-01-16 21:43
It seems your terminal is not being properly detected as TTY. I'll look into it and see if I can reproduce.

**Comment by amcaplan** [comment] 2023-01-18 09:54
This was quite the rabbit hole. Bottom line, [Node doesn't play nicely with Windows terminal emulators](https://github.com/nodejs/node/issues/3006). You can work around this with the following alias:

```sh
alias shopify="winpty $(which shopify).cmd"
```

Hope this workaround solves it for you, let me know!

**Comment by ankurzayed** [comment] 2023-02-03 15:02
Thank you very much. It worked for me. i was too frustrated for the error. finally solved. Thank you again.

**Comment by toomuchcoffeehah** [comment] 2023-02-08 17:38
process.stdin.setRawMode is not a function

**Comment by isaacroldan** [comment] 2023-02-21 13:53
Since the issue seems to be on node and there is a workaround for it, i'll close it. Feel free to open a new issue if there are new problems with non-TTY terminals and windows.

**Closed by isaacroldan** 2023-02-21 13:53 UTC
Labels: Type: Bug, Area: @shopify/cli-kit, State: Waiting for feedback

**Comment by obligado86** [comment] 2023-05-25 13:21
I got same problem running shopify theme dev command on git bash. but when I tried using cmd it works.

**Comment by amcaplan** [comment] 2023-05-29 11:20
@obligado86 see [my comment above](https://github.com/Shopify/cli/issues/1111#issuecomment-1386776366). `git bash` doesn't expose stdin correctly. Best to use cmd or powershell.

@pablogiralt I'm not sure what's causing this, please open a new issue with full details and we'll do our best to help!
