### ISSUE TITLE
[Bug]: New node app creates both package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by meandillar** [Shopify/cli#154] opened 2022-07-13 21:54 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Creating a new app using `npm init @shopify/app@latest -- --template node` should only create package-lock.json and not a yarn.lock

### Actual behavior

Creates both a package-lock.json and yarn.lock. Running `npm run dev` results in `Error: Cannot find module 'graphql'`

Removing yarn.lock, package-lock.json and node_modules, then running `npm install` fixes the error.

### Stack trace

```shell
upsell (node:internal/modules/cjs/loader:933
extensions |   const err = new Error(message);
extensions |               ^
extensions | 
extensions | Error: Cannot find module 'graphql'
extensions | Require stack:
extensions | - /Users/org/node_modules/graphql-tag/lib/graphql-tag.umd.js
extensions | - /Users/org/node_modules/graphql-tag/main.js
extensions | - /Users/org/Sites/upsell/node_modules/@luckycatfactory/esbuild-graphql-loader/lib/index.js
extensions | - /Users/org/Sites/upsell/node_modules/@shopify/shopify-cli-extensions/build.js
extensions | - /Users/org/Sites/upsell/node_modules/@shopify/shopify-cli-extensions/cli.js
extensions |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
extensions |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
extensions |     at Module.require (node:internal/modules/cjs/loader:1005:19)
extensions |     at require (node:internal/modules/cjs/helpers:102:18)
extensions |     at /Users/org/node_modules/graphql-tag/lib/graphql-tag.umd.js:2:103
extensions |     at Object.<anonymous> (/Users/org/node_modules/graphql-tag/lib/graphql-tag.umd.js:5:2)
extensions |     at Module._compile (node:internal/modules/cjs/loader:1103:14)
extensions |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
extensions |     at Module.load (node:internal/modules/cjs/loader:981:32)
extensions |     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
extensions |   code: 'MODULE_NOT_FOUND',
extensions |   requireStack: [
extensions |     '/Users/org/node_modules/graphql-tag/lib/graphql-tag.umd.js',
extensions |     '/Users/org/node_modules/graphql-tag/main.js',
extensions |     '/Users/org/Sites/upsell/node_modules/@luckycatfactory/esbuild-graphql-loader/lib/index.js',
extensions |     '/Users/org/Sites/upsell/node_modules/@shopify/shopify-cli-extensions/build.js',
extensions |     '/Users/org/Sites/upsell/node_modules/@shopify/shopify-cli-extensions/cli.js'
extensions |   ]
extensions | })
```

### Reproduction steps

1. Run `npm init @shopify/app@latest -- --template node` to create a new app
2. Run `npm run dev`

### Operating System

Mac OS Big Sur

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.2.0

### Node version (run `node -v` if you're not sure)

16.14.0

**Comment by gonzaloriestra** [comment] 2022-07-14 12:01
Hi! Thanks for creating the issue.

I'm not able to reproduce it, and I'm also using Mac OS, Cli 3.2.0, Node 16.14.0... I followed your reproduction steps, but it didn't create a `yarn.lock` and `npm run dev` worked without any additional step.

Could you please try again with `--verbose` and share the output?

**Comment by meandillar** [comment] 2022-07-14 21:00
Hey, thanks for the reply. After further investigation I realised the yarn.lock file was getting created after scaffolding a Checkout UI Extension with the command `npm run scaffold extension`

**Comment by gonzaloriestra** [comment] 2022-07-15 07:38
@meandillar thanks! You are right, the scaffold is generating both files, we'll have a look.

However, I'm still not able to see that error. Have you seen that again? If you can share detailed reproduction steps, it would be very helpful.

**Comment by pepicrft** [comment] 2022-07-22 13:48
@meandillar I noticed in your stacktrace that you have Node dependencies at `/Users/org/node_modules/`. In particular, you have one, `/Users/org/node_modules/graphql-tag/`, and it's making [this logic](https://github.com/Shopify/shopify-cli-extensions/blob/main/packages/shopify-cli-extensions/src/build.ts#L67) believe that the dependency is present when it turns out it's not. You can either delete `/Users/org/node_modules` or run `npm install` in that directory assuming that you have a `package.json` that contains `graphql-tag`. 
After you do that the issue should go away.

**Comment by gonzaloriestra** [comment] 2022-08-01 08:54
@meandillar regarding the [issue you mentioned about the yarn.lock created after scaffolding an extension](https://github.com/Shopify/cli/issues/154#issuecomment-1184892453), it should be fixed in the next release. Related PR: https://github.com/Shopify/cli/pull/218.

**Comment by pepicrft** [comment] 2022-11-08 12:40
Closing this issue since it's already been addressed. Feel free to create a new issue if the problem arises again.

**Closed by pepicrft** 2022-11-08 12:40 UTC
Labels: Type: Bug, State: Waiting for feedback, no-issue-activity
