### ISSUE TITLE
[Bug]: Errno::EACCES: Permission denied - bind(2) for 127.0.0.1:9292

### ISSUE THREAD

**Issue by leaderfrank** [Shopify/cli#4308] opened 2024-08-10 12:50 UTC
![image](https://github.com/user-attachments/assets/fc27f86b-86f9-498e-bc52-5a59b1746504)

I don't know what is exactly the error if I run `shopify app diploy` it is working fine.

But in the `shopify app div` it works but after few seconds it show this error and stop the development process.

**Comment by amcaplan** [comment] 2024-08-12 08:09
Hi @leaderfrank, this looks like an issue with pushing theme files.

To help debug this, here's what I'll suggest:

1. Go [here](https://github.com/Shopify/cli/issues/new/choose) and file a bug report instead, using the correct template. This will instruct you to include all the relevant information we need to help.
2. Run the CLI in `--verbose` mode, and it's best to add `SHOPIFY_CLI_STACKTRACE=1` to your environment as well. Then you can see more about where exactly the issue is coming from.

I'm going to close this issue and encourage you to open a new one with full details, per the above instructions. Please trust me that this will help us move much more quickly towards resolution steps.

**Closed by amcaplan** 2024-08-12 08:09 UTC
