### ISSUE TITLE
[Bug]: Can't log in as a customer via the Shopify CLI

### ISSUE THREAD

**Issue by UribeJr** [Shopify/cli#4270] opened 2024-08-05 16:26 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Booting up my local host via shopify theme dev, I should be able to log into a customer account for development via a logged in customer state.

### Actual behavior

When I try to log in, it only refreshes the login page. Have tried multiple browsers and themes, can't seem to get logged in. 

### Verbose output

```shell
shopify theme dev
```

### Reproduction steps

1.Shopify theme pull -s [store_name]
2.shopify theme dev (fire up the server)
3.log into a customer account
4. doesn't log me in, just refreshes the page. 

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.65.1

**Comment by mgmanzella** [comment] 2024-08-09 14:07
👋 thanks for reporting this issue, im able to reproduce and am investigating the root cause

**Comment by yhc44** [comment] 2024-08-23 10:17
Hello, i have the same issue. Can you say anythting about it @mgmanzella ?

**Comment by montalvomiguelo** [comment] 2024-08-28 12:47
Same same, pushed a fix @mgmanzella

**Closed as completed** 2024-08-30 08:22 UTC
Labels: Type: Bug, Area: @shopify/theme, Theme Sev-2, #gsd:40767

**Comment by yhc44** [comment] 2024-09-09 10:14
Hello, i still have the same issue. Anyone else here?
