### ISSUE TITLE
[Bug]: failing to build "ERROR  Cannot read properties of null (reading 'useContext')"

### ISSUE THREAD

**Issue by niinpatel** [Shopify/cli#2998] opened 2023-10-19 10:17 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

start the dev server as expected

### Actual behavior

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

  ERROR  Cannot read properties of null (reading 'useContext')

 node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21

 1615:     }
 1616:   }
 1617:
 1618:   return dispatcher.useContext(Context);
 1619: }
 1620: function useState(initialState) {
 1621:   var dispatcher = resolveDispatcher();

 - useContext (node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21)
 - useStdin (node_modules/@shopify/app/node_modules/ink/build/hooks/use-stdin.js:6:24)
 - Dev (node_modules/@shopify/app/dist/cli/services/dev/ui/components/Dev.js:14:53)
 - renderWithHooks (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:7478:18)
 - mountIndeterminateComponent (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:11247:13)
 - beginWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:12760:16)
 - beginWork$1 (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:19569:14)
 - performUnitOfWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18703:12)
 - workLoopSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18609:5)
 - renderRootSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18577:7)

```

### Reproduction steps

1. `npm run dev`
2.
3.

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

    "@shopify/cli": "^3.49.7",

### Shell

iterm2

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

NodeJS

**Comment by paragopinath** [comment] 2023-10-19 15:01
+1

**Comment by NathanJolly** [comment] 2023-10-19 19:44
+1, subscribed

```
nathanoliveira@Nathans-MacBook-Pro pos-e2e-ui-extension % yarn shopify --version
yarn run v1.22.19
$ shopify --version
@shopify/cli/3.50.0 darwin-arm64 node-v20.8.1
```

**Comment by matteodepalo** [comment] 2023-10-20 08:45
Also a bit more context will help us understand as we cannot reproduce this with new apps. Is this with a new app? Did you choose the remix template or not? Which extensions do you have? Can you paste the content of your package.json files?

**Comment by niinpatel** [comment] 2023-10-20 09:42
> Is this with a new app?

no

> Did you choose the remix template or not?

I don't know what that means, I think no.

> Which extensions do you have?

"@shopify/checkout-ui-extensions-react": "^0.27.0",

 > Can you paste the content of your package.json files?

```
{
  "name": "checkout-custom-fields",
  "version": "1.0.0",
  "main": "web/index.js",
  "license": "UNLICENSED",
  "scripts": {
    "shopify": "shopify",
    "build": "shopify app build",
    "dev": "shopify app dev",
    "info": "shopify app info",
    "generate": "shopify app generate",
    "deploy": "shopify app deploy",
    "test": "npm test --prefix web"
  },
  "dependencies": {
    "@shopify/app": "^3.49.7",
    "@shopify/checkout-ui-extensions-react": "^0.27.0",
    "@shopify/cli": "^3.49.7",
    "react": "^17.0.2"
  },
  "author": "nitinpatel",
  "overrides": {
    "@types/react": "17.0.30"
  },
  "husky": {
    "hooks": {
      "pre-commit": "echo 'Running pre-commit hook...' && npx prettier . --write"
    }
  },
  "devDependencies": {
    "husky": "^8.0.2"
  }
}
```

**Comment by niinpatel** [comment] 2023-10-20 09:51
the exact version seems to be 3.50.0

**Comment by NathanJolly** [comment] 2023-10-20 15:38
For some additional context, I agree with @niinpatel that 3.48.4 works, but any 3.49.x did not.

**Comment by remy727** [comment] 2023-11-02 13:36
`3.48.2` works

**Comment by isaacroldan** [comment] 2023-11-03 10:49
I'll close this issue because it's a duplicate of https://github.com/Shopify/cli/issues/2809
A solution was provided there: 
```
For other folks having this issue, another workaround would be to remove react 17 from the top level package.json, remove node_modules AND remove package-lock.json.
```
If you use a different package manager, be sure to remove the correspondent lock file

**Closed by isaacroldan** 2023-11-03 10:49 UTC
Labels: Type: Bug

**Comment by Hermes-fire** [comment] 2025-04-18 00:41
`ncu --interactive --target minor` fix this
