### ISSUE TITLE
[Bug]: Internal server error on using development store via Shopify CLI on developing themes

### ISSUE THREAD

**Issue by danimoralespdp** [Shopify/cli#1343] opened 2023-02-10 08:09 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should have displayed my theme on a development store.

### Actual behavior

I've followed all the steps for using CLI while developing themes. In fact it has worked for me before with other stores, but it just stopped working.

I get servel internal error (see screenshot) and got no idea on how to solve the issue.

![Captura de pantalla_20230210_084438](https://user-images.githubusercontent.com/123565302/218035630-58ff5c5e-4773-445a-a6fa-91969f1878fd.png)

### Reproduction steps

1. Connect to your store and go to theme dev with the command `shopify theme dev --store yourstore.myshopify.com`
2. Once executed, open a browser window with copy pasting the url they give you.

### Operating System

Windows 11 PRO

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.42.0

### Node version (run `node -v` if you're not sure)

v14.17.5

**Comment by gonzaloriestra** [comment] 2023-02-10 09:08
Hi, thanks for creating the issue.

Could you run it with `--verbose` and share the log?

**Comment by danimoralespdp** [comment] 2023-02-10 09:27
Of course @gonzaloriestra, thank you

[log.txt](https://github.com/Shopify/cli/files/10705810/log.txt)

**Comment by gonzaloriestra** [comment] 2023-02-14 09:46
Looking at the log, I can see a couple of issues that should be fixed in the latest release (3.43.0). Could you please upgrade and try again?

**Comment by KCBos** [comment] 2023-02-17 09:30
Unfortunately got the same issue as above;
- Windows 11 and WSL ubuntu 
- CLI version 3.43.0
- npm 8.19.3
- node v16.19.1
- ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

[log.txt](https://github.com/Shopify/cli/files/10765233/log.txt)

**Comment by danimoralespdp** [comment] 2023-02-17 09:38
@gonzaloriestra I keep having the same issue after upgrading. I ran it again and got the log:
[log2.txt](https://github.com/Shopify/cli/files/10765291/log2.txt)

**Comment by danimoralespdp** [comment] 2023-02-28 07:18
@pegaro OMG! I can't believe it worked. For some reason switching accounts also worked for me. It's a bit of a mess working this way but at least now I can use it normally. 

Thank you very much!

**Comment by gonzaloriestra** [comment] 2023-02-28 09:12
I'm sorry that we weren't able to help, but we couldn't reproduce it and we were a bit lost. I'm closing then.

@Shopify/theme-developer-tools maybe there's a way to show a better error in this case.

**Closed by gonzaloriestra** 2023-02-28 09:12 UTC
Labels: Type: Bug, Area: @shopify/theme, windows

**Comment by danimoralespdp** [comment] 2023-04-25 06:52
> I had a very similar Internal Server Error (with a different name). I lost over 1 hour but I was able to solve it by going to Chrome Cookie settings and deleting all cookies for address 127.0.0.1

It worked! I cannot believe. Thank you very much akerd.
