### ISSUE TITLE
[Bug]: @shopify/app v3.35.0 "deploy" command fails with unexpected error

### ISSUE THREAD

**Issue by kevin-aminzadeh** [Shopify/cli#1146] opened 2023-01-18 23:48 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

App should be deployed successfully.

### Actual behavior

**Deploy script fails with the following error:**
``` 
The Partners GraphQL API responded unsuccessfully with the HTTP status 200 and errors:
    [ 
      {                                    
        "message": "Unexpected system error", 
        "extensions": {                                           
           "code": "500"                                           
         }                                                         
      }                                                            
    ] 
```

**This error is also sometimes returned in Spanish:**
``` 
The Partners GraphQL API responded unsuccessfully with the HTTP status 200 and errors:
    [                                                           
      {                                    
        "message": "Error inesperado del sistema", 
        "extensions": {                                           
           "code": "500"                                           
         }                                                         
      }                                                            
    ]
```

The error also only occurs when `@shopify/app v3.35.0` is used. The following dependency config for example, works as expected:
```		
"@shopify/app": "3.34.0",
"@shopify/cli": "3.35.0",
```

### Stack trace

```shell
at (graphql-request/src/index.ts:410)         
       throw new ClientError(                                    
     at step (graphql-request/dist/index.js:63)                  
       op = body.call(thisArg, _);                               
     at next (graphql-request/dist/index.js:44)                  
       function verb(n) { return function (v) { return step([n,  
        v]); }; }                                                
     at fulfilled (graphql-request/dist/index.js:35)             
       function fulfilled(value) { try {                         
       step(generator.next(value)); } catch (e) { reject(e); }   
       }                                                         
     at processTicksAndRejections                                
     (node:internal/process/task_queues:95)
```

### Reproduction steps

1. Create new app boilerplate using `npm init @shopify/app@latest`
2. Create a new extension inside app using `npm run shopify app generate extension`
3. Run `npm run deploy` to try to deploy the app & extension

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.35.0

### Shell

Gitbash

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Node 18.12.1

**Comment by irahulranjan** [comment] 2023-01-19 11:52
Same here, Once I got the error message in Japanese as well. 予期しないシステムエラー

**Comment by amcaplan** [comment] 2023-01-19 17:11
This should be fixed in 3.36.0. Please comment or open a new issue if an upgrade doesn't solve the issue for you.

**Closed by amcaplan** 2023-01-19 17:11 UTC
Labels: Type: Bug

**Comment by EtraEllecon** [comment] 2023-01-24 19:51
Hi @amcaplan I just started receiving this error. Deployed fine an hour ago and now getting it. Shopify CLI `3.36.1`

**Comment by tiagocdr** [comment] 2023-01-24 20:17
Hi! I'm having the same issue with @shopify/cli and @shopify/app 3.36.0, used also the latest 3.36.2 and didn't work.

**Comment by VictorAtoms** [comment] 2023-01-24 20:58
Same here, already updated to 3.36.2, and still wont work.

**Comment by EtraEllecon** [comment] 2023-01-24 21:37
Works for me now! Just took some time I guess.

**Comment by meltinbit** [comment] 2023-01-31 18:38
same here with "@shopify/app": "3.39.0", "@shopify/cli": "3.39.0"

**Comment by olivierbouchard** [comment] 2023-01-31 19:00
Same issue here, can't publish theme app extension

**Comment by Alex-bml** [comment] 2023-01-31 19:17
The same problem.
shopify CLI 3.39.0

**Comment by amcaplan** [comment] 2023-01-31 19:34
Thanks all for the continued reports! The CLI is fine in the latest version, but there seems to be an incident happening on the API side, and I've confirmed that our team is looking into it.

**Comment by iamvishnusankar** [comment] 2023-02-26 03:15
@amcaplan Any updates on this?

**Comment by amcaplan** [comment] 2023-02-26 14:12
@iamvishnusankar this incident was done after a few hours. If you're still experiencing similar results, please open a new issue.

I'll lock so new problems can be surfaced more visibly with new issues.
