### ISSUE TITLE
[Bug]: "spawn Unknown system error" when running "npm run dev" on new app

### ISSUE THREAD

**Issue by krjo** [Shopify/cli#1817] opened 2023-04-15 18:01 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Running `npm run dev` should start up a dev server to preview my app

### Actual behavior

`npm run dev` throws an error

### Verbose output

```shell
Error: Command failed with Unknown system error -86: /Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/plugin-cloudflare/bin/cloudflared tunnel --url http://localhost:51733 --no-autoupdate
spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/execa/index.js:84:26)
    at buildExec (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/cli-kit/dist/public/node/system.js:80:28)
    at exec (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/cli-kit/dist/public/node/system.js:35:28)
    at file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:60:9
    at new Promise (<anonymous>)
    at tunnel (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:30:12)
    at Object.hookStart [as action] (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:15:31)
    at Object.<anonymous> (file:///Users/kj/Code/_apps/sunday-scaries-checkout-ui/node_modules/@shopify/cli-kit/dist/public/node/plugins/tunnel.js:16:24)
```

### Reproduction steps

1. Following Shopify's tutorial on setting up a checkout ui extension. Run `npm init @shopify/app@latest`
2. `cd` into app directory
3. `npm run shopify app generate extension`
4. Choose `No, connect it to an existing app` and select app.
5. Select development store to preview app. The store has the checkout extensibility developer preview.
6. Hit enter. Error is thrown.

### Operating System

Mac OS Ventura 13.3.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

Node

**Comment by matteodepalo** [comment] 2023-04-18 08:34
Hi @krjo, there seems to be a problem when starting the Cloudflare tunnel on your machine. Could you try starting a tunnel manually to see if the issue is not related to the CLI? To do so you can run:

```
brew install cloudflared
cloudflared tunnel --url http://localhost:8080
```

**Comment by krjo** [comment] 2023-04-18 15:45
Hi Matteo, I ran that and here's what I got. I'm not familiar with Cloudlfare so I very much appreciate the help:

```cloudflared tunnel --url http://localhost:8080
2023-04-18T15:44:24Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2023-04-18T15:44:24Z INF Requesting new quick Tunnel on trycloudflare.com...
2023-04-18T15:44:25Z INF +--------------------------------------------------------------------------------------------+
2023-04-18T15:44:25Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2023-04-18T15:44:25Z INF |  https://lay-bride-db-electricity.trycloudflare.com                                        |
2023-04-18T15:44:25Z INF +--------------------------------------------------------------------------------------------+
2023-04-18T15:44:25Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2023-04-18T15:44:25Z INF Version 2023.4.1
2023-04-18T15:44:25Z INF GOOS: darwin, GOVersion: go1.19.8, GoArch: arm64
2023-04-18T15:44:25Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8080]
2023-04-18T15:44:25Z INF cloudflared will not automatically update if installed by a package manager.
2023-04-18T15:44:25Z INF Generated Connector ID: 7af8c22b-164e-4624-ab54-bf192e25200d
2023-04-18T15:44:25Z INF Initial protocol quic
2023-04-18T15:44:25Z INF ICMP proxy will use 192.168.4.180 as source for IPv4
2023-04-18T15:44:25Z INF ICMP proxy will use fe80::1c15:7585:ce6a:bb97 in zone en0 as source for IPv6
2023-04-18T15:44:25Z INF Created ICMP proxy listening on 192.168.4.180:0
2023-04-18T15:44:25Z INF Created ICMP proxy listening on [fe80::1c15:7585:ce6a:bb97%en0]:0
2023-04-18T15:44:25Z INF Starting metrics server on 127.0.0.1:60189/metrics
2023-04-18T15:44:25Z ERR update check failed error="no release found"
2023-04-18T15:44:26Z INF Registered tunnel connection connIndex=0 connection=6c4d58dd-7a29-4490-a982-997343c66952 event=0 ip=198.41.192.27 location=LAX protocol=quic```

**Comment by nickoutram** [comment] 2023-04-20 23:51
Hi @matteodepalo, I've run into the same issue trying to work on an app on a fresh M2 MacBook Air and following the same reproduction steps as original report (connecting to an existing app). Same OS, Shopify and shell setup as original poster.

Here's the output from creating a tunnel manually: 

```2023-04-20T23:49:23Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2023-04-20T23:49:23Z INF Requesting new quick Tunnel on trycloudflare.com...
2023-04-20T23:49:24Z INF +--------------------------------------------------------------------------------------------+
2023-04-20T23:49:24Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2023-04-20T23:49:24Z INF |  https://conflicts-defendant-warren-who.trycloudflare.com                                  |
2023-04-20T23:49:24Z INF +--------------------------------------------------------------------------------------------+
2023-04-20T23:49:24Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2023-04-20T23:49:24Z INF Version 2023.4.1
2023-04-20T23:49:24Z INF GOOS: darwin, GOVersion: go1.19.8, GoArch: arm64
2023-04-20T23:49:24Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8080]
2023-04-20T23:49:24Z INF cloudflared will not automatically update if installed by a package manager.
2023-04-20T23:49:24Z INF Generated Connector ID: 788cf6ab-9b25-4add-8852-b263e2d9776d
2023-04-20T23:49:24Z INF Initial protocol quic
2023-04-20T23:49:24Z INF ICMP proxy will use 192.168.0.243 as source for IPv4
2023-04-20T23:49:24Z INF ICMP proxy will use fe80::1030:63a1:eb90:48b6 in zone en0 as source for IPv6
2023-04-20T23:49:24Z INF Created ICMP proxy listening on 192.168.0.243:0
2023-04-20T23:49:24Z INF Created ICMP proxy listening on [fe80::1030:63a1:eb90:48b6%en0]:0
2023-04-20T23:49:24Z INF Starting metrics server on 127.0.0.1:50177/metrics
2023-04-20T23:49:25Z ERR update check failed error="no release found"
2023-04-20T23:49:25Z INF Registered tunnel connection connIndex=0 connection=ebaba73f-4f8c-4fba-b20e-ce67b7f7de76 event=0 ip=198.41.200.43 location=SYD protocol=quic
```

Then running `npm run dev --tunnel-url=https://conflicts-defendant-warren-who.trycloudflare.com` seems to result in the same error:

```
Error: Command failed with Unknown system error -86: /Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/plugin-cloudflare/bin/cloudflared tunnel --url http://localhost:50195 --no-autoupdate
spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/execa/index.js:84:26)
    at buildExec (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/cli-kit/dist/public/node/system.js:80:28)
    at exec (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/cli-kit/dist/public/node/system.js:35:28)
    at file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:60:9
    at new Promise (<anonymous>)
    at tunnel (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:30:12)
    at Object.hookStart [as action] (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/plugin-cloudflare/dist/tunnel.js:15:31)
    at Object.<anonymous> (file:///Users/nickoutram/Desktop/Shopify/t/node_modules/@shopify/cli-kit/dist/public/node/plugins/tunnel.js:16:24)
```

**Comment by matteodepalo** [comment] 2023-04-21 07:43
You should be able to run 3.44 temporarily as that version introduced Cloudflare tunnels. I'd recommend against using a cli version less than that.

@nickoutram thank you for the reproduction I'll be looking into it.

**Comment by wisniewski94** [comment] 2023-04-21 13:29
In my opinion, you should check if you can run `cloudflared` service which is being spawned by CLI when you use cloudflare plugin. Here are the docs:
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/#prerequisites

If you google -86 status code, you will find that it's common to M1/M2 users and some report that rosetta helps to overcome the issue

`softwareupdate --install-rosetta`

Finding out if it works will help narrow down our bug hunting :)

**Comment by krjo** [comment] 2023-04-21 16:29
> --tunnel=ngrok

`npm run dev --tunnel=ngrok` returned the same error. I'll look into Rosetta.

**Comment by nickoutram** [comment] 2023-04-21 23:40
@wisniewski94 can confirm installing rosetta via this single prompt fixed and `npm run dev` works as expected now, thanks :)

**Comment by krjo** [comment] 2023-04-26 21:16
@matteodepalo Confirming that installing Rosetta resolved this error.

**Comment by matteodepalo** [comment] 2023-04-28 10:32
Great! Closing this issue then 👍

**Closed by matteodepalo** 2023-04-28 10:32 UTC
Labels: Type: Bug, Area: @shopify/app

**Comment by uxgnod** [comment] 2023-05-10 02:01
> I ran npm audit fix --force, and Shopify CLI was set back to v3.23.0. This version runs as expected and does not produce the original error.

🎉cool ! 
Fixed the same error on new M2 Pro with `npm audit fix --froce`
