### ISSUE TITLE
CLI app Build Command Giving Error [Bug]

### ISSUE THREAD

**Issue by varun-etraffic** [Shopify/cli#1788] opened 2023-04-11 06:53 UTC
Hello Everyone,

I have been working on an app using Shopify CLI and tried to generate a build using `npm run build` command. But I was getting the Environment variable SHOPIFY_API_KEY not defined error. Then I found the solution for it by running the command like this `SHOPIFY_API_KEY=<KEY> npm run build`

This command now giving me this error `Error coming from 'composer build'` and I am not able to find a solution to resolve this as I need to create the build of the to deploy it on cloudways hosting web server.

I thought I may have done something wrong in my development that is why I am facing this issue but when I created fresh app run the command I faced the same thing on a fresh app too.

**ERROR:** Attached is the full error message.
[Error.log](https://github.com/Shopify/cli/files/11197484/Error.log)

**Mechine Details:**
Device: Dell Vostro
OS: Windows 10

Please help me resolve this issue as soon as possible.

**Comment by alvaro-shopify** [comment] 2023-04-11 12:18
Hi @varun-etraffic . Thanks for rising up this issue. I think that the problem is that the php template does not support Windows properly. Let me ping the @Shopify/client-libraries-app-templates for visibility.

There are two problems in this case.
* backend build process is run in parallel with the frontend one. However the backend one depends on the output of the frontend to run this `ln -sf ../frontend/dist/assets public/assets && ln -sf ../frontend/dist/index.html public/index.html`. The workaround is building manually the frontend, access `/web/frontend` and run `npm run build`. You should see that the `dist` folder content is generated in the log output

* backend build process runs a command that is not adapted to Windows `ln -sf ../frontend/dist/assets public/assets && ln -sf ../frontend/dist/index.html public/index.html`. For now, you should modify in the file `web/composer.json` the content of the script `build-frontend-links` to be `mklink /J .\\public\\assets .\\frontend\\dist\\assets  && mklink /H .\\public\\index.html .\\frontend\\dist\\index.html`. You have to make sure that the `.\public\assets` and the  `.\public\index.tml` sysmlinks does not exist before running the `build` command. If that's the case you should delete them previously.

Please let me know if this works for you.

**Comment by varun-etraffic** [comment] 2023-04-12 05:34
Hi @alvaro-shopify 

Thanks for getting back, I tried the first solution and getting this error https://prnt.sc/yw8t066TNepG and I didn't understand the second solution could you please elaborate that a little more what exactly I need to do in that so that I can try that out too.

Thanks,
Varun

**Comment by varun-etraffic** [comment] 2023-04-12 11:01
Hello @alvaro-shopify 

The build is generated, I passed the absolute file Path of the assets and index.html file in the  `web/composer.json` file `build-frontend-links` and it has has solved the problem and build was generated successfully. We can close this issue now.

Thanks for you Time and Efforts hope this will resolved soon in the next update of the CLI. 😊

**Comment by alvaro-shopify** [comment] 2023-04-12 13:48
@varun-etraffic , I'm glad you could finally make it work.

I will leave this issue opened and assigned to @Shopify/client-libraries-app-templates. They will evaluate if it's needed to adapt the `php` template to work in Windows.

**Comment by varun-etraffic** [comment] 2023-05-05 03:43
Hi,

Is there any update on this as the github action bot is going to close issue but we didn't hear after that if this is resolvable or not for windows operating sytem.

**Closed** 2023-06-04 03:35 UTC
Labels: no-issue-activity, Area: Client Libraries and App Templates
