### ISSUE TITLE
[Bug]: The theme app extension can no longer find assets.

### ISSUE THREAD

**Issue by Yamashou** [Shopify/cli#3344] opened 2024-02-01 00:57 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I would like to be able to npm run deploy.

### Actual behavior

Only the Theme App Extension has an error.

### Verbose output

```shell
2024-02-01T00:53:37.936Z: Creating directory at /private/var/folders/v2/k_ddyzwx76736rs3zqp4dyfr0000gn/T/422b0f2258894781ea41a0ccaf514f4e...
2024-02-01T00:53:37.936Z: Sync-creating directory at /private/var/folders/v2/k_ddyzwx76736rs3zqp4dyfr0000gn/T/d1f943f3d04eb08fe401e55171a260d7/bundle...
2024-02-01T00:53:37.937Z: Creating an empty file at /private/var/folders/v2/k_ddyzwx76736rs3zqp4dyfr0000gn/T/d1f943f3d04eb08fe401e55171a260d7/bundle/.shopify...
reservation-ui           │ Running theme check on your Theme app extension...
Failed to get file size: Error: ENOENT: no such file or directory, stat 'assets/index.js'
reservation-ui           │
reservation-ui           │ Bundling theme extension reservation-ui...
2024-02-01T00:53:38.026Z: Copying file from extensions/reservation-ui/assets/index.js to /private/var/folders/v2/k_ddyzwx76736rs3zqp4dyfr0000gn/T/d1f943f3d04eb08fe401e55171a260d7/bundle/583513e6-dc17-4394-9305-f4dd24fc1cfc/assets/index.js...
```

### Reproduction steps

1. Update to the latest version (3.55.1) from 3.52.0
2. npm run deploy

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.55.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.10.0

```[tasklist]
### Tasks
```

**Comment by charlespwd** [comment] 2024-02-01 15:04
> Failed to get file size: Error: ENOENT: no such file or directory, stat 'assets/index.js'

Is there a reference to index.js that doesn't resolve? This might be thrown by our [`fileSize` util](https://github.com/Shopify/theme-tools/blob/c786b7eaf0939b2d9b9469b66a74d45f56e626c1/packages/theme-check-node/src/file-utils.ts#L13-L21) 

By the `AssetSizeAppBlockJavaScript` check in here: https://github.com/Shopify/theme-tools/blob/c786b7eaf0939b2d9b9469b66a74d45f56e626c1/packages/theme-check-common/src/checks/asset-size-app-block-javascript/index.ts#L31

Which checks that the file referenced by 
```
{% schema %}
{
  "javascript": "index.js"
}
{% endschema %}
```

Has a size within the bounds allocated. It's throwing an error because it can't find that file.

**Comment by javi-pastor** [comment] 2024-02-07 14:28
Same problem here, dont know if this will affect to deploy or only it's a warning

**Comment by charlespwd** [comment] 2024-02-09 13:11
@isaacroldan, it looks like we're doing something out of order in `shopify app deploy`

https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/deploy.ts#L87-L119

Given that some folks have some kind of build process tacked on top of their theme app extension, I think we should run theme-check _after_ that build process. The problem above occurs because the `copying file` happens _after_ running theme-check and not before. We should build, then validate and not the other way around.

**Comment by charlespwd** [comment] 2024-02-09 13:16
`this.build(options)` has a branch that runs themeCheckRun before `bundleThemeExtension` happens?

**Comment by charlespwd** [comment] 2024-02-09 13:17
Maybe I'm misunderstanding what does what.

**Comment by br34th3r** [comment] 2024-02-16 10:30
Same issue here but no build steps prior. Just an update of the CLI and API versions from `3.48.x` to `3.56.1` our static assets just aren't found anymore. Is it a cacheing issue? As the files are expected to be found but just aren't (even though the path spat back out by the STDERR is correct and the files exist there). it shouldn't know that those files are there unless they're stored in memory, in which case did the file structure for theme app extensions change in the recent updates?

**Comment by br34th3r** [comment] 2024-02-16 11:05
In response to this, I've tried symlinking the entire assets directory into the root of the app and no dice. Alongside that I then tried each subdirectory heading towards the original theme app extension UI assets folder. Still no dice. It just doesn't seem to be finding the files for whatever reason, but I also can't tell if that's true or not as the files could be being found, but it's just failing a small check that is inconsequential to the deploy and those files are being deployed anyway... Any updates on this @charlespwd ?

**Comment by charlespwd** [comment] 2024-02-20 15:05
Hmm. @kirillplatonov If that's really the case then maybe it's just a matter of the theme check run not running at the correct root? 

Can someone give me the following:
- Exact set of commands that cause the problem
- The exact layout of their files (preferably using `tree`), I'm not concerned about the non-TAE but I'd like to have something from .git root

I vaguely recall having logic in place for finding the root of a TAE (https://github.com/Shopify/theme-tools/blob/main/packages/theme-language-server-node/src/dependencies.ts#L32-L35)

But it looks like we only use that in the language server. That might be the issue actually. We don't infer the correct root for TAE and so the thing breaks. 

Ah crap so it looks like the config is hardcoded but the root isn't set properly: https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/build/theme-check.ts#L68-L69

There's unfortunately no config way to fix this because of that (we don't even read the config). I believe that was by design and is indeed a problem.

**Comment by tsimoshka** [comment] 2024-02-20 15:45
> If that's really the case then maybe it's just a matter of the theme check run not running at the correct root?

@charlespwd Yes, It seems to be the case. And it is consistent with my observations in the [my previous comment](https://github.com/Shopify/cli/issues/3344#issuecomment-1939022016)

> Exact set of commands that cause the problem

You can reproduce it with the freshly bootstrapped application like this:

```bash
pnpm create @shopify/app -d pnpm -p . --template=remix --name=test-theme-ext-error --flavor=javascript
cd test-theme-ext-error
pnpm generate extension --name=theme_ext # pick the theme app extension for type of extension when asked
# init asset
echo "console.log('blah');" > extensions/theme-ext/assets/test.js
# init block using this asset
echo '{% schema %}
  {
    "name": "Test",
    "target": "body",
    "javascript": "test.js",
    "settings": []
  }
{% endschema %}
' > extensions/theme-ext/blocks/test.liquid
# run the build (error should be in ouput)
pnpm shopify app build
# link assets to the root of project
ln -s $PWD/extensions/theme-ext/assets $PWD/assets
# run build again (no error)
pnpm shopify app build
```

**Comment by chris-taffi** [comment] 2024-02-29 04:54
Is there any update on this issue?

**Comment by ryanm-bw** [comment] 2024-02-29 04:56
This issue just killed our app on several high-profile Plus stores, really need to fix asap please!

**Comment by ryanm-bw** [comment] 2024-02-29 05:04
> Any update for this issue? I have assets in `extensions/theme-app-extension/assets` folder and I suddenly started getting the same error:
> 
> ```shell
> Failed to get file size: Error: ENOENT: no such file or directory, stat 'assets/collection-swatches.js'
> Failed to get file size: Error: ENOENT: no such file or directory, stat 'assets/product-swatches.js'
> ```
> 
> It breaks deployment from the CI: ![CleanShot 2024-02-20 at 09 04 51@2x](https://private-user-images.githubusercontent.com/839922/306180853-27cadeae-e78d-4ec3-8e8a-16734a8999e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODI2OTMsIm5iZiI6MTcwOTE4MjM5MywicGF0aCI6Ii84Mzk5MjIvMzA2MTgwODUzLTI3Y2FkZWFlLWU3OGQtNGVjMy04ZThhLTE2NzM0YTg5OTllNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQwNDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWJiNDI3YjEyM2RlNDBiMGY2ODZlNjA2MjgxNWE0OWI3Y2M3OTg5MDAyNmQwNGI4ZjZiZDM5NTE0N2MxMGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QSa4Lx2CCISfv1qhQHdYVYQZeWBbknoyRinivU0IW0E)
> 
> Moving assets folder to root helped but it's really ugly workaround which kills existing conventions. Can we get a proper fix in CLI?

Thank you for the tip to move the assets folder to the root - at least we can get our app back up and running while this issue gets fixed!

**Comment by chris-taffi** [comment] 2024-02-29 05:19
@ryanm-bw Revert @shopify/app and @shopify/cli version to 3.52.0 fixed this for me but the issue needs to be fixed soon.

**Comment by thatdom** [comment] 2024-02-29 08:24
+1

**Comment by daviareias** [comment] 2024-02-29 13:48
> > Moving assets folder to root helped but it's really ugly workaround which kills existing conventions. Can we get a proper fix in CLI?
> 
> Thank you for the tip to move the assets folder to the root - at least we can get our app back up and running while this issue is fixed!

I don't think it will be fixed soon, unless everybody spams support. I pretty much posted everywhere you can imagine about this issue (slack,discord, facebook,twitter...) , and gave up after 24 hours.

Is still happening in every embedded app, it seems to happens more often in stores that recently installed the app.

**Comment by charlespwd** [comment] 2024-02-29 13:55
Guys... I'm closing this discussion. Let me cook.

**Closed as completed** 2024-03-01 14:01 UTC
Labels: Type: Bug, Area: @shopify/theme
