### ISSUE TITLE
[Bug]: `shopify theme dev` CORS and HMR errors

### ISSUE THREAD

**Issue by kenji-twp** [Shopify/cli#1354] opened 2023-02-12 05:21 UTC
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

- No CORS errors
- HMR works normally
- Can access Cart API (eg: /cart/update.js) in the localhost preview (eg: at https://127.0.0.1:9292)

### Actual behavior

HMR is not working properly, possibly due to CORS errors (that I didn't have before version <3.38 roughly). There are lots of errors are showing in console – note the bottom two lines, it's returning a 401 error when I just try to add a product to cart:

<img width="1275" alt="Screenshot 2023-02-12 at 3 04 17 pm" src="https://user-images.githubusercontent.com/111416569/218294208-3771f84f-c613-4ffe-bce7-eefbb6a9d896.png">

No idea how to fix this. I didn't change any theme code, and this was working fine in previous versions... so it makes me think there's something wrong with CLI authentication or CORS or CLI Ruby?

Not sure, but might be related to #1343

### Stack trace

```shell
kenji % SHOPIFY_CLI_STACKTRACE=1 shopify theme dev --path=src --store=<REDACTED> --theme=122631749741 --password=<REDACTED> --verbose
2023-02-12T05:03:22.717Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@1.21.0 argv: [ '--path=src', '--store=<REDACTED>', '--theme=122631749741', '--password=<REDACTED>', '--verbose' ] +0ms
2023-02-12T05:03:22.729Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-02-12T05:03:22.734Z: Obtaining the dependency manager in directory /Users/kenji/Dev/<REDACTED>...
2023-02-12T05:03:22.736Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/kenji/Dev/<REDACTED>

2023-02-12T05:03:23.089Z: Analytics event sent: {
  "command": "theme dev",
  "time_start": 1676178202718,
  "time_end": 1676178202732,
  "total_time": 14,
  "success": true,
  "cli_version": "3.43.0",
  "ruby_version": "3.2.1",
  "node_version": "19.6.0",
  "is_employee": false,
  "uname": "darwin arm64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/theme\"]",
  "env_shell": "zsh",
  "env_device_id": "2872e235535e04836bff70a7b12c8a364c8bee7c",
  "env_cloud": "localhost",
  "env_package_manager": "yarn",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--path=src --store=<REDACTED> --theme=122631749741 --password=<REDACTED> --verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-02-12T05:03:23.089Z: Completed command theme dev
2023-02-12T05:03:25.740Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/kenji/Dev/<REDACTED>

2023-02-12T05:03:25.760Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Users/kenji/Dev/<REDACTED>

2023-02-12T05:03:25.871Z: Creating directory at /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0...
2023-02-12T05:03:25.871Z: Writing some content to file at /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/Gemfile...
2023-02-12T05:03:25.872Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle config set --local path /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0
  · Working directory: /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0

2023-02-12T05:03:25.952Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /Users/kenji/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0

2023-02-12T05:03:26.104Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec shopify theme serve /Users/kenji/Dev/<REDACTED>/src --theme 122631749741 --live-reload hot-reload
  · Working directory: /Users/kenji/Dev/<REDACTED>

┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ DEBUG GET https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json with X-Request-Id: ab8c3a26-fe28-4f5a-b29b-36a224b28420
┃ * Syncing theme #122631749741 on <REDACTED>.myshopify.com
┃ DEBUG GET https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes/122631749741/assets.json with X-Request-Id: 3be1ea5a-3026-4f7e-ba19-1d4d76b5870e
┃                                                                                                        100%
┃ 
┃ Serving /Users/kenji/Dev/<REDACTED>/src
┃ 
┃ Please open this URL in your browser:
┃ http://127.0.0.1:9292
┃ 
┃ Customize this theme in the Theme Editor, and use 'theme pull' to get the changes:
┃ https://<REDACTED>.myshopify.com/admin/themes/122631749741/editor
┃ 
┃ Share this theme preview:
┃ https://<REDACTED>.myshopify.com/?preview_theme_id=122631749741
┃ 
┃ (Use Ctrl-C to stop)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.08s) ━━
[2023-02-12 15:03:28] INFO  WEBrick 1.7.0
[2023-02-12 15:03:28] INFO  ruby 3.2.1 (2023-02-08) [arm64-darwin22]
[2023-02-12 15:03:28] INFO  WEBrick::HTTPServer#start: pid=10361 port=9292
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://theme-kit-access.shopifyapps.com/cli/sfr/?preview_theme_id=122631749741&_fd=0&pb=0
DEBUG `-> 302 request_id: 44fc8e55-d1bd-42dc-b451-d77f651d2009
DEBUG Proxying GET https://theme-kit-access.shopifyapps.com/cli/sfr/?_fd=0&pb=0
DEBUG `-> 200 request_id: e92524c4-1bbf-404a-bb66-d94c0daa1d0a
DEBUG [HotReload] Connected to SSE stream
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying GET https://theme-kit-access.shopifyapps.com/cli/sfr/web-pixels-manager@0.0.216/sandbox/?_fd=0&pb=0
DEBUG Proxying GET https://theme-kit-access.shopifyapps.com/cli/sfr/web-pixels-manager@0.0.216/sandbox/worker.modern.js?_fd=0&pb=0
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG `-> 400 request_id: 766f6f21-bfea-43b0-a1e4-9e3512d30270
DEBUG `-> 400 request_id: 584af6f7-6442-42c8-b80f-c022d80a4640
DEBUG `-> 400 request_id: c9a71544-0f99-4181-b10b-ac034f376daa
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/unstable/produce_batch?_fd=0&pb=0
DEBUG `-> 200 request_id: ccf7442f-8cbd-4a86-9e2f-0570ac24e729
DEBUG `-> 200 request_id: 554b65b2-97e6-4476-99ab-81d8f872910c
DEBUG `-> 400 request_id: 11323032-97be-480b-a450-2f96e2b2841a
DEBUG `-> 400 request_id: 6ff30724-fa2a-427f-abe9-25b2e28c364b
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/.well-known/shopify/monorail/v1/produce?_fd=0&pb=0
DEBUG `-> 400 request_id: 1f444d4d-3445-479f-8f9f-11180ea3c7f6
DEBUG Proxying GET https://theme-kit-access.shopifyapps.com/cli/sfr/cart?_fd=0&pb=0
DEBUG `-> 200 request_id: aceb4fd6-90fc-4b8d-915f-b36ffc793a7f
DEBUG Proxying POST https://theme-kit-access.shopifyapps.com/cli/sfr/cart/update.js?_fd=0&pb=0
DEBUG `-> 401 request_id: 3012e3b1-0f4a-4fde-9868-2e1b91077ec3
^CDEBUG Stop signal: "SIGINT"
Stopping…
DEBUG Stop signal: "SIGTERM"
Stopping…

kenji % [2023-02-12 15:04:31] INFO  going to shutdown ...
[2023-02-12 15:04:31] INFO  WEBrick::HTTPServer#start done.
```

### Reproduction steps

1. Run `shopify theme dev` with `--store` and `--password`
2. Open the local preview in your browser
3. Check if HMR works and if there are any CORS errors in the console, and possibly trying to access shopify APIs (eg: Cart API).

### Operating System

MacOS Ventura 13.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.19.0

**Comment by mgmanzella** [comment] 2023-02-16 23:38
👋 hi @kenji-twp, thanks for reporting this issue! i'm able to reproduce the issue so thank you for all the helpful information. 

the 400s you're seeing in your console are noisy but don't appear to be related to the reason the cart isn't previewing.

this issue seems to be related to the theme access app so i was able to successfully hot reload the cart related templates/ add to cart by excluding the `--password` param. if possible, id authenticate via the browser in the meantime instead of using your theme access token. however, let me know if this temporary workaround doesn't work 🙏

**Comment by iPhenan** [comment] 2023-02-19 20:12
> Im getting the same issue without using Theme Access app or the `--password` flag, I even tried to logout and relogin but still get the same issues mentionned above, here is my console screen.
> 
> When I disable **HOT RELOAD**, these issues disappear however. I hope this could help.
> 
> <img alt="Shopify CLI 3 issue" width="1363" src="https://user-images.githubusercontent.com/63895927/219962109-675f6ae1-ebc4-43d3-b06d-f3a75aed139e.png">

Same issue here. Using Apple Silicon + Homebrew Shopify CLI 3.0, latest version (3.43.0)

**Comment by james0r** [comment] 2023-02-20 00:09
Also getting CORS errors and hot-reloading failing. Also noticing that `shopify theme dev --live-reload full-page` seems to try hot-reloading still but fails and does a full round trip anyway.

Apple Silicon + Homebrew install
Current Shopify CLI version: 3.43.0

<img width="567" alt="image" src="https://user-images.githubusercontent.com/34731936/219983697-2839b521-04a1-4943-8802-bda0ef8555ff.png">

**Comment by mgmanzella** [comment] 2023-02-21 21:05
just an update -- the CORS error was fixed via [this PR](https://github.com/Shopify/cli/pull/1370) (see original issue [here](https://github.com/Shopify/cli/issues/1119)), however this fix isn't live yet in the CLI. 

however the issue i linked didn't stop HMR from working, so ill continue to investigate.

**Comment by gonzaloriestra** [comment] 2023-03-03 08:36
Ok, it should work now (it doesn't require a CLI upgrade). Please, let us know if you find any other issue.

**Closed by gonzaloriestra** 2023-03-03 08:36 UTC
Labels: Type: Bug, Area: @shopify/theme

**Comment by james-julius** [comment] 2023-03-20 19:21
Hot reload was working great for me until suddenly it stopped a week ago. Any fresh theme extensions created (I am using a theme extension) also show the same `CORS` issue. I can see from your PR linked that one of the things to test is the `hot-reload` URL shouldn't be called twice, and unfortunately it is.
<img width="881" alt="Screenshot 2023-03-20 at 12 20 45 PM" src="https://user-images.githubusercontent.com/41165086/226444137-8b7c4297-dea0-4fa4-ba5d-ce84d02df135.png">

**Comment by james-julius** [comment] 2023-03-22 19:17
@Poitrin thanks for the follow-up. Appreciate it. Good to know that it's been working without CORS. Tried your `shopify-nightly` fix but unfortunately it doesn't run `shopify-nightly app dev` so unusable for me. Weirdly, something has stopped HMR working in my code, so I may open another issue in that case
