### ISSUE TITLE
[Bug]: The Admin GraphQL API responded unsuccessfully with errors

### ISSUE THREAD

**Issue by magify-expert-shopify** [Shopify/cli#5094] opened 2024-12-12 12:19 UTC
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Pull the code from shopify to locale

### Actual behavior

API Error

```
 The Admin GraphQL API responded unsuccessfully with errors:                 │
│                                                                              │
│  [                                                                           │
│    {                                                                         │
│      "message": "Internal error. Looks like something went wrong on our      │
│  end.\nRequest ID: 7b5e6663-37f6-48d2-a7b7-c2dc2fd07b1d-1734005670 (include  │
│   this in support requests).",                                               │
│      "extensions": {                                                         │
│        "code": "INTERNAL_SERVER_ERROR",                                      │
│        "requestId": "7b5e6663-37f6-48d2-a7b7-c2dc2fd07b1d-1734005670"        │
│      }                                                                       │
│    }                                                                         │
│  ]
```

### Verbose output

<details>
  <summary>Verbose output</summary>

  ```
> shopify theme pull --store muscsoyeux --theme Magify --ignore package.json


╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                      │
│                                                                                                      │
│  The Admin GraphQL API responded unsuccessfully with errors:                                         │
│                                                                                                      │
│  [                                                                                                   │
│    {                                                                                                 │
│      "message": "Internal error. Looks like something went wrong on our end.\nRequest ID:            │
│  f7fa983d-7cb2-4686-9fd6-a288c8a949ef-1734005682 (include this in support requests).",               │
│      "extensions": {                                                                                 │
│        "code": "INTERNAL_SERVER_ERROR",                                                              │
│        "requestId": "f7fa983d-7cb2-4686-9fd6-a288c8a949ef-1734005682"                                │
│      }                                                                                               │
│    }                                                                                                 │
│  ]                                                                                                   │
│                                                                                                      │
│  Request ID: f7fa983d-7cb2-4686-9fd6-a288c8a949ef-1734005682                                         │
│                                                                                                      │
│                                                                                                      │
│  To investigate the issue, examine this stack trace:                                                 │
│    at makeRequest                                                                                    │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-D4DJJ4PZ.js:27246)          │
│    at processTicksAndRejections (node:internal/process/task_queues:95)                               │
│    at async makeVerboseRequest                                                                       │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-D4DJJ4PZ.js:27276)          │
│    at async retryAwareRequest                                                                        │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-D4DJJ4PZ.js:27363)          │
│    at (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-3QKHLZPS.js:3453)        │
│    at (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-3IUDQUHD.js:29973)       │
│    at async fetchThemeAssets                                                                         │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/index.js:149387)                  │
│    at async downloadFiles                                                                            │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/index.js:154237)                  │
│    at async runTask2                                                                                 │
│    (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-3IUDQUHD.js:31282)          │
│    at (Users/Admin/AppData/Roaming/npm/node_modules/@shopify/cli/dist/chunk-3IUDQUHD.js:31296)       │
│                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯

  ```

</details>

### Reproduction steps

1. Run  `shopify theme pull` command
2.
3.

### Operating System

Windows 11

### Shopify CLI version (`shopify --version`)

@shopify/cli/3.72.0 win32-x64 node-v22.5.1

### Shell

PowerShell

### Node version (run `node -v` if you're not sure)

v22.5.1

### What language and version are you using in your application?

ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x64-mingw32]

**Comment by azycimo** [comment] 2024-12-12 19:48
Duplicate of #5031. Temporary solution is to downgrade Shopify CLI. In that thread, it's downgrade to `3.70.0`, but I had to go back to `3.69.x` to get `theme pull` working again.

**Comment by Waynenabors** [comment] 2024-12-16 20:47
I have another one from today if it helps `3cf80078-66db-4a1a-9d0d-f984cd5a403b-1734380135`

**Closed as completed** 2024-12-16 22:46 UTC
Labels: Severity: 2, Type: Bug, Area: @shopify/theme
